[".config/tmux/plugins/tpm"]
  type = "archive"
  url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".config/zsh/plugins/zsh-defer"]
  type = "archive"
  url = "https://github.com/romkatv/zsh-defer/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".config/zsh/plugins/zsh-completions"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".config/zsh/plugins/zsh-better-npm-completion"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".config/zsh/plugins/anyframe"]
  type = "archive"
  url = "https://github.com/mollifier/anyframe/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".config/zsh/plugins/autosuggestions"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".config/zsh/plugins/syntax-highlighting"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".config/zsh/fpath/aws_zsh_completer.sh"]
  type = "file"
  url = "https://raw.githubusercontent.com/aws/aws-cli/v2/bin/aws_zsh_completer.sh"
  refreshPeriod = "168h"

[".config/zsh/plugins/ni.zsh"]
  type = "file"
  url = "https://raw.githubusercontent.com/azu/ni.zsh/main/ni.zsh"
  refreshPeriod = "168h"

[".config/prh-rules/media/WEB+DB_PRESS.yml"]
  type = "file"
  url = "https://raw.githubusercontent.com/prh/rules/master/media/WEB+DB_PRESS.yml"
  refreshPeriod = "168h"

[".local/bin/win32yank.exe"]
  type = "archive-file"
  url = "https://github.com/equalsraf/win32yank/releases/download/v0.1.1/win32yank-x64.zip"
  path = "win32yank.exe"
  executable = true
  refreshPeriod = "168h"
