[settings]
experimental = true
idiomatic_version_file_enable_tools = ["terraform"]

[settings.npm]
bun = true

[tools]
bun = "latest"
claude = "latest"
deno = "latest"
elixir = "latest"
erlang = "latest"
ghc = "latest"
go = "latest"
gradle = "latest"
helm = "latest"
java = "latest"
julia = "latest"
kotlin = "latest"
lua-language-server = "latest"
node = "22"
opentofu = "latest"
pnpm = "latest"
pulumi = "latest"
python = "3.13"
ruby = "latest"
rye = "latest"
scala = "latest"
shellcheck = "latest"
shfmt = "latest"
terraform = ["1.0.11", "1.5.7", "latest"]
terraform-ls = "latest"
tflint = "latest"
tfsec = "latest"
uv = "latest"
zig = "latest"

"aqua:aws/aws-cli" = { version = "latest", symlink_bins = true }

"cargo:cargo-audit" = "latest"
"cargo:cargo-chef" = "latest"
"cargo:cargo-compete" = "latest"
"cargo:cargo-crev" = "latest"
"cargo:cargo-deny" = "latest"
"cargo:cargo-expand" = "latest"
"cargo:cargo-features-manager" = "latest"
"cargo:cargo-generate" = "latest"
"cargo:cargo-lambda" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:cargo-machete" = "latest"
"cargo:cargo-make" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-sort" = "latest"
"cargo:cargo-udeps" = "latest"
"cargo:cargo-update" = "latest"
"cargo:https://github.com/Feel-ix-343/markdown-oxide.git" = { version = "latest", locked = true }
"cargo:stylua" = "latest"
"cargo:usage-cli" = "latest"

"go:github.com/d-kuro/gwq/cmd/gwq" = "latest"
"go:github.com/k1LoW/git-wt" = "latest"
"go:github.com/mattn/memo" = "latest"
"go:github.com/rhysd/vim-startuptime" = "latest"
"go:golang.org/x/tools/gopls" = "latest"

"npm:@astrojs/language-server" = "latest"
"npm:@astrojs/ts-plugin" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:@marp-team/marp-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:atcoder-cli" = "latest"
"npm:bash-language-server" = "latest"
"npm:cspell" = "latest"
"npm:mcp-hub" = "latest"
"npm:md-to-pdf" = "latest"
"npm:prettier" = "latest"

"pipx:poetry" = "latest"
"pipx:pyright" = "latest"
"pipx:ruff" = "latest"
