[general]
import = ["alacritty-theme/themes/iceberg.toml"]

[colors]
transparent_background_colors = true

[window]
dynamic_padding = true
opacity = 0.85

[window.padding]
x = 8
y = 4

[cursor]
thickness = 0.18

[font]
size = 16

[font.bold]
family = "UDEV Gothic NF"

[font.bold_italic]
family = "Hack Nerd Font Mono"

[font.italic]
family = "Hack Nerd Font Mono"

[font.normal]
family = "Hack Nerd Font Mono"

[[keyboard.bindings]]
key = "Comma"
mods = "Command"

[keyboard.bindings.command]
args = ["-c", "open ~/.config/alacritty/alacritty.yml"]
program = "sh"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[terminal.shell]
args = ["-l", "-c", "/opt/homebrew/bin/tmux a -t 0 || /opt/homebrew/bin/tmux -u"]
program = "/bin/zsh"
